// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: api/api-stream.proto

package composeserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File1 []byte `protobuf:"bytes,1,opt,name=File1,proto3" json:"File1,omitempty"`
	File2 []byte `protobuf:"bytes,2,opt,name=File2,proto3" json:"File2,omitempty"`
	File3 []byte `protobuf:"bytes,3,opt,name=File3,proto3" json:"File3,omitempty"`
}

func (x *FileList) Reset() {
	*x = FileList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileList) ProtoMessage() {}

func (x *FileList) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileList.ProtoReflect.Descriptor instead.
func (*FileList) Descriptor() ([]byte, []int) {
	return file_api_api_stream_proto_rawDescGZIP(), []int{0}
}

func (x *FileList) GetFile1() []byte {
	if x != nil {
		return x.File1
	}
	return nil
}

func (x *FileList) GetFile2() []byte {
	if x != nil {
		return x.File2
	}
	return nil
}

func (x *FileList) GetFile3() []byte {
	if x != nil {
		return x.File3
	}
	return nil
}

type FilePDF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []byte `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
}

func (x *FilePDF) Reset() {
	*x = FilePDF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilePDF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePDF) ProtoMessage() {}

func (x *FilePDF) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePDF.ProtoReflect.Descriptor instead.
func (*FilePDF) Descriptor() ([]byte, []int) {
	return file_api_api_stream_proto_rawDescGZIP(), []int{1}
}

func (x *FilePDF) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

var File_api_api_stream_proto protoreflect.FileDescriptor

var file_api_api_stream_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x32,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x32, 0x12, 0x14, 0x0a,
	0x05, 0x46, 0x69, 0x6c, 0x65, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x46, 0x69,
	0x6c, 0x65, 0x33, 0x22, 0x1d, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x44, 0x46, 0x12, 0x12,
	0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x46, 0x69,
	0x6c, 0x65, 0x32, 0x4d, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x0a,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x50, 0x44, 0x46, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x73, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x44, 0x46, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x10, 0x5a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_api_stream_proto_rawDescOnce sync.Once
	file_api_api_stream_proto_rawDescData = file_api_api_stream_proto_rawDesc
)

func file_api_api_stream_proto_rawDescGZIP() []byte {
	file_api_api_stream_proto_rawDescOnce.Do(func() {
		file_api_api_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_api_stream_proto_rawDescData)
	})
	return file_api_api_stream_proto_rawDescData
}

var file_api_api_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_api_stream_proto_goTypes = []interface{}{
	(*FileList)(nil), // 0: composeserver.FileList
	(*FilePDF)(nil),  // 1: composeserver.FilePDF
}
var file_api_api_stream_proto_depIdxs = []int32{
	0, // 0: composeserver.Server.ComposePDF:input_type -> composeserver.FileList
	1, // 1: composeserver.Server.ComposePDF:output_type -> composeserver.FilePDF
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_api_stream_proto_init() }
func file_api_api_stream_proto_init() {
	if File_api_api_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_api_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilePDF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_api_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_api_stream_proto_goTypes,
		DependencyIndexes: file_api_api_stream_proto_depIdxs,
		MessageInfos:      file_api_api_stream_proto_msgTypes,
	}.Build()
	File_api_api_stream_proto = out.File
	file_api_api_stream_proto_rawDesc = nil
	file_api_api_stream_proto_goTypes = nil
	file_api_api_stream_proto_depIdxs = nil
}
